on: [push]

jobs:
  Json_file_read_job:
    runs-on: windows-latest
    name: A job to read a json file
    steps:
      - uses: actions/checkout@v3
      - id: read-json
        uses: ./
        with:
          json-file: 'test.json'
      - run: echo "${{ fromJSON(steps.read-json.outputs.json-contents).test }}"