on: [push]

jobs:
  Json_file_read_job:
    runs-on: ubuntu-latest
    name: A job to read a json file
    steps:
      - uses: actions/checkout@v3
      - id: read-json
        uses: ajuanicorena/json-loader@v1
        with:
          json-file: 'config.json'
      - run: echo "One value fromJSON ${{ fromJSON(steps.read-json.outputs.json-contents).<key to read> }}"